In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

2.7.0


In [5]:
a = tf.constant([2,4,5,6] , shape=(2,2))
print(a)

tf.Tensor(
[[2 4]
 [5 6]], shape=(2, 2), dtype=int32)


In [6]:
b = tf.constant([5,7,8,9] , shape=(2,2))
print(b)

tf.Tensor(
[[5 7]
 [8 9]], shape=(2, 2), dtype=int32)


In [8]:
final = tf.concat([a , b] , 0)
print(final)

tf.Tensor(
[[2 4]
 [5 6]
 [5 7]
 [8 9]], shape=(4, 2), dtype=int32)


In [9]:
label1 = tf.repeat(0 , 10)
label2 = tf.repeat(1,10)

tf.Tensor([0 0 0 0 0 0 0 0 0 0], shape=(10,), dtype=int32)
